name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use action from organization repository
        uses: orginfratec/action_file/action@master
        with:
          repository: orginfratec/action_file
          token: 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
          ref: main
          path: action_file
