name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use action from organization repository
        uses: orginfratec/action_file/action@master
        with:
          repository: orginfratec/action_file
          token: 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
          ref: main
          path: action_file
