name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
      
env:
  SONAR_TOKEN: sqa_f658ef5fbb92484d00c5b2331c21cfe09830404e
  SONAR_HOST_URL: http://54.73.70.164:9000
  SONAR_PROJECT_KEY: testsonar2
  secrets: inherit
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      sonar.projectKey: testsonar
    steps:
      - name: List Files
        run: |
           pwd
           ls -a
           echo "azhar"
           echo azher
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-token: ${{ env.SONAR_TOKEN }}
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
        
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
