name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
      
env:
  SONAR_TOKEN: squ_92ce500b4383353ef21219293c07ffff35128a09
  SONAR_HOST_URL: http://54.73.70.164:9000
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      sonar.projectKey: testsonar
    steps:
      - name: Set Repository Name Variable
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Use Repository Name Variable
        run: echo "Repository Name:${{ env.REPO_NAME }}"
        
      - name: Create SonarQube project
        run: |
          curl --include --request POST -u ${{ env.SONAR_TOKEN }}: '${{ env.SONAR_HOST_URL }}/api/projects/create?name=${{ env.REPO_NAME }}&project=${{ env.REPO_NAME }}'
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create SonarQube properties file
        run: echo "sonar.projectKey=${{ env.REPO_NAME }}" > sonar-project.properties
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-token: ${{ env.SONAR_TOKEN }}
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
