name: my-workflow

on:
  push:
    branches:
      - master

jobs:
  build_and_scan:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Build and Scan
        uses: anas203044/global/globalaction@main
